### ISSUE TITLE
Make logic of keeping off screen Nodes alive configurable

### ISSUE THREAD

**Issue by KovalevAndrey** [bumble-tech/appyx#111]
Keeping all Nodes in the NavModel alive while they're invisible can be memory consuming. We need to make it configurable. Twitter thread for the reference: https://twitter.com/Piwai/status/1563157989430661122?s=20&t=FoQaDoEPift8J2TGkqOuGQ

**Comment by saket** [comment]
+1 for this. I ran into this yesterday when I was trying to only keep fullscreen nodes in memory that have a transparent background.
