### ISSUE TITLE
Support ComponentActivity for Jetpack Compose projects

### ISSUE THREAD

**Issue by Ninjars** [bumble-tech/appyx#131]
`NodeActivity` extends `AppCompatActivity`, whereas `ComponentActivity` used in Jetpack Compose template projects does not. This impedes adoption of Appyx in new projects.

Furthermore, `ActivityIntegrationPoint` (the integration with which is the sole purpose of `NodeActivity`) requires `AppCompatActivity` as a parameter, preventing a user simply creating their own wrapper.

It looks like `ActivityIntegrationPoint` could just take `Activity` as its first parameter, making it more re-usable, and it should also be possible to provide a convenient boilerplate equivalent for `NodeActivity` that extends `ComponentActivity`, for use in Jetpack Compose projects.

**Comment by CherryPerry** [comment]
Both sounds reasonable.
`AppComponentActivity` adds unnecessary fragment management.
