### ISSUE TITLE
onBackPressed memory leak

### ISSUE THREAD

**Issue by duanemalcolm** [bumble-tech/appyx#181]
When I quit my app using the back button on a phone running SDK 29, Leak Canary reports a memory leak.

If I use the fix reported here: https://issuetracker.google.com/issues/139738913, the leak is fixed.
```
override fun onBackPressed() {
        // Fix for Memory Leak: https://issuetracker.google.com/issues/139738913
        if (Build.VERSION.SDK_INT == 29 && !onBackPressedDispatcher.hasEnabledCallbacks()) {
            finishAfterTransition()
        } else {
            super.onBackPressed()
        }
    }
```

However, if I use Appyx NodeActivity with a RootNode, I get the memory leak again.

**Comment by CherryPerry** [comment]
> Leak Canary reports a memory leak

The leak you are talking about is a framework leak that is added to LeakCanary ignore list – `AndroidReferenceMatchers.IREQUEST_FINISH_CALLBACK`.

The fix involves `onBackPressedDispatcher`, `fragmentManager` and `isTaskRoot`, so I would prefer to keep it as part of application code (depending on your particular case).

If you think it is reasonable to add the fix to your code, you can add it to your activity that extends from `NodeActivity`.

**Comment by duanemalcolm** [comment]
Thanks for the reply @CherryPerry .

I agree this should be fixed in my code but I couldn't work out how and didn't understand Appyx enough to work it out. Essentially, without Appyx (Code block A below) there was no leak but when I substitute Appyx (Code block B) I get the leak.

I tried using the `onBackPressedDispatcher` and checking the fragments but it still leaked.

My final solution was to manually dispose the leaking object inside the `MainScreen` using `DisposableEffect.onDispose`. It was a coroutine launch that was collecting a flow which I manually cancelled.

Code A:
```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            MyTheme() {
                Surface(color = MaterialTheme.colors.background) {
                    MainScreen()
                }
            }
        }
    }

    override fun onBackPressed() {
       // Fix for Memory Leak: https://issuetracker.google.com/issues/139738913
        if (Build.VERSION.SDK_INT == 29 && !onBackPressedDispatcher.hasEnabledCallbacks()) {
            finishAfterTransition()
        } else {
            super.onBackPressed()
        }
    }
}
```

Code B:
```
class MainActivity : NodeActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            MyTheme() {
                Surface(color = MaterialTheme.colors.background) {
                    NodeHost(integrationPoint = integrationPoint) {
                        RootNode(buildContext = it) // contains MainScreen
                    }
                }
            }
        }
    }

    override fun onBackPressed() {
       // Fix for Memory Leak: https://issuetracker.google.com/issues/139738913
        if (Build.VERSION.SDK_INT == 29 && !onBackPressedDispatcher.hasEnabledCallbacks()) {
            finishAfterTransition()
        } else {
            super.onBackPressed()
        }
    }
}
```

**Comment by CherryPerry** [comment]
Please provide fully reproducible sample.

**Comment by duanemalcolm** [comment]
Sorry for the slow reply. It took me a while to find `NodeComponentActivity`.

Anyway, I tried to replicate my leaking code with a simple example but couldn't. Maybe it was because I'm using a `ComponentActivity` instead of an `AppCompatActivity`, KMM or some other complexity in my code.

I have a solution to stop the leak so I think we can close this report and if I find something in the future, I'll post it here.

Thanks for your help.

**Comment by duanemalcolm** [comment]
I tried a `ComponentActivity` in my main code and it didn't make a difference, so it is caused by something else.
