### ISSUE TITLE
Backstack history/state is lost on orientation changes for nested parent nodes

### ISSUE THREAD

**Issue by RationalRank** [bumble-tech/appyx#235]
The top parent node's backstack is not restored properly upon orientation changes. 
This can be reproduced in the latest commit (1.x branch), in the official sandbox backstack sample, but the same cannot be reproduced in alpha release (1.0-alpha09 or for 1.0.0-rc01 tag commit)

**Using 1.0-alpha09 (Backstack is restored properly upon orientation changes)**

https://user-images.githubusercontent.com/14078609/196938063-7923910a-b03e-456a-af36-fa31701f5ec4.mp4

**Using the latest commit (1.x branch) (Backstack is reset to initial `NavTarget`)**

https://user-images.githubusercontent.com/14078609/196938117-718e7863-399a-4b11-9c5f-8ef1b5983aa0.mp4

**Comment by zsoltk** [comment]
Hey @devv911 thanks for the detailed investigation and video, we'll look into it!

**Comment by RationalRank** [comment]
I am adding a few more observations here. I can reproduce this issue from version `1.0-alpha07`. Backstack seems to restore properly with `1.0-alpha06`

I've created a sample app to reproduce
https://github.com/devv911/AppyxNodeNestingBackstackIssue
