### ISSUE TITLE
Codelabs css / js is broken

### ISSUE THREAD

**Issue by zsoltk** [bumble-tech/appyx#265]
All our codelabs linked from https://bumble-tech.github.io/appyx/how-to-use-appyx/codelabs/ started rendering as plain html files.

<img width="704" alt="Screen Shot 2022-11-01 at 00 19 27" src="https://user-images.githubusercontent.com/238198/199134242-2f49f7da-2e73-4201-ba8b-1279e1447f3e.png">

**Comment by zsoltk** [comment]
Seems to be on Google's side they removed these assets: 

https://groups.google.com/g/codelab-authors/c/WwSdRF4bjBE

**Comment by LachlanMcKee** [comment]
@zsoltk / @vladcipariu91 it seems to be fixed

**Comment by zsoltk** [comment]
We solved it by self-hosting those files as google suggested in the above linked thread, so we don't depend on them.
