### ISSUE TITLE
Replicating startDestinationRoute.popUpto() from compose navigation

### ISSUE THREAD

**Issue by KotlinGeekDev** [bumble-tech/appyx#271]
Hello maintainers. 
Thanks a lot for this library!
It really simplifies work a lot, and I am replacing navigation-compose with it.
However, I want to know if there is a way to 
replicate what startDestinationRoute.popUpto() in navigation compose does. 
That is, when navigating to 3 different screens sequentially, on tapping the back button on the 3rd screen, I should come back to the first screen.
Thanks again!

**Comment by KovalevAndrey** [comment]
Hi @KotlinGeekDev, thanks for the feedback! 

Yes, it's possible. Although Appyx does not provide this, you can implement your own `BackStackOperation` to support this behaviour. For the reference, you could take a look at how `Pop` is implemented. It should be really straightforward to implement `PopUpTo` operation

**Comment by KotlinGeekDev** [comment]
Thanks @KovalevAndrey I will have a look.

**Comment by KotlinGeekDev** [comment]
Still trying to understand how to use it. I have a bottom nav bar where I will use it, but struggling to understand how to make it work such that it navigates to the target destination, but applies the popUpto(), when pressing the back button.
 cc @KovalevAndrey

**Comment by KotlinGeekDev** [comment]
I went for a simple solution: Using a BackHandler in each target screen, with the code to navigate back to the first target screen.

**Comment by KovalevAndrey** [comment]
@KotlinGeekDev you can actually use [`singleTop`](https://bumble-tech.github.io/appyx/navmodel/backstack/#single-top) operation provided by Appyx. It will do what you need

**Comment by KotlinGeekDev** [comment]
@KovalevAndrey I thought the same as well, but for some reason it did not work for me.
Maybe I am doing something wrong?:thinking:

**Comment by KovalevAndrey** [comment]
@KotlinGeekDev can you please provide details how are you using it and what's not working for you? (end result)

**Comment by KotlinGeekDev** [comment]
@KovalevAndrey Here is the code(line 104): https://github.com/KotlinGeekDev/Nosky/blob/revamp-navigation-arch/app/src/main/java/kt/nostr/nosky_compose/MainActivity.kt

**Comment by KotlinGeekDev** [comment]
In the onClick function for each BottomNavItem, I navigate to the desired destination. When I navigate to 3 different destinations, singleTop() acts like Push(per the docs). So there is no out of the box solution to go back to the first destination from the 3rd destination directly.

**Comment by KotlinGeekDev** [comment]
> I went for a simple solution: Using a BackHandler in each target screen, with the code to navigate back to the first target screen.

That is why I went with this 'simple' solution. 😅

**Comment by KovalevAndrey** [comment]
@KotlinGeekDev please check out latest 1.x branch, launch `samples.sandbox` and open `NavModel examples` -> `Backstack example`. There you can play with a back stack, using `singleTop` operation. At the bottom of the screen you'll see visual representation of the back stack that should help with understanding of which elements are in back stack

**Comment by KotlinGeekDev** [comment]
OK @KovalevAndrey thanks. Will check it out.
