### ISSUE TITLE
Update ReadME - Where is "Get started?"

### ISSUE THREAD

**Issue by osh91** [bumble-tech/appyx#286]
Hi, 
I am newbie to this and I went to your website and tried to find a page where I can get started like calling libraries inside Gradle:app and so forth but I can't find it. It would be nice if you guys could update better from the web page to here. Thanks

**Comment by imashnake0** [comment]
https://bumble-tech.github.io/appyx/releases/downloads/#downloads

**Comment by zsoltk** [comment]
Hey @OshedheMunasinghe, the documentation got updated with more links to the Downloads page + having the latest version badge shown there too. Let us know if you have any more questions!
