### ISSUE TITLE
Node does is missing onDestroy callback in some cases

### ISSUE THREAD

**Issue by KovalevAndrey** [bumble-tech/appyx#293]
More info [here](https://github.com/bumble-tech/appyx/discussions/292#discussioncomment-4283832)

Similarly, can be reproduced following these steps:
1. Open sample sandbox
2. Click explicit navigation button
3. Click `Push two`
4. In `Grandchild one` click `Navigate to child one`
5. Observe lifecycle events in the logs. On destroy is not received

**Comment by dimsuz** [comment]
This kept happening for me on `1x` snapshot and so while trying to come up with the minimal example, I have found that I've actually misguided you :(

I wasn't using `backStack.newRoot()`, but rather I was using `backStack.singleTop()`. 
But still, this `singleTop` call should result in a _completely new hierarchy_ where even the root node is different from the previously active one, and so I believe it still should call `onDestroy` on inactive ones?

Here I've build a [one-file sample](https://gist.github.com/dimsuz/bb2540c753c710a23a76eb9e39d57382) which you can insert in some project, then make that activity a default one and run the app.

Steps to reproduce:
1. Click on buttons until you arrive to the "main screen"
2. Observe the following in logs:
```
[Login] node onCreate
[Login] node onStart
[Permissions] node onCreate
[Permissions] node onStart
[Main] node onCreate
[Main] node onStart
[Login] node onStop
[Permissions] node onStop
```
As you can see in the end, `onDestroy` is not called after `singleTop()` → only `onStop`
If you switch `singleTop` to `newRoot`, then `onDestroy` is called.

**Comment by KovalevAndrey** [comment]
@dimsuz I've just checked out your example and it look like you're using `singleTop(Main)` while backStack has active `Login` navTarget. It results in `LoginNode` subtree moving into `STASHED`, not `DESTOYED` state which is correct. 

Please check out [singleTop documentation](https://bumble-tech.github.io/appyx/navmodel/backstack/#single-top) to see the expected behaviour

**Comment by dimsuz** [comment]
Oh! :facepalm: Indeed, I don't know why I expected `singleTop` to work like `newRoot`. So everything works as it should!

I guess this issue can be safely closed then. Thanks for all the help!
