### ISSUE TITLE
Compatibility with JetBrains Compose Multiplatform

### ISSUE THREAD

**Issue by manosbatsis** [bumble-tech/appyx#31]
Apologies for abusing the issues to ask a question; I was wondering whether appyx is or can be made compatible with [Compose Multiplatform](https://github.com/JetBrains/compose-jb)?

**Comment by zsoltk** [comment]
Hey @manosbatsis! Yes, it's on our radar and is being discussed.

**Comment by manosbatsis** [comment]
Still new to kmm but appyx would be useful. Happy help with testing, migrating samples etc.

**Comment by eygraber** [comment]
Any news on this?

**Comment by zsoltk** [comment]
All Appyx modules are now multiplatform, closing as done.
