### ISSUE TITLE
lifecycle field now required in Node?

### ISSUE THREAD

**Issue by charlie-niekirk** [bumble-tech/appyx#350]
I've written a "proper child node" like this:

```
class AddServerNode(
    buildContext: BuildContext
) : Node(buildContext = buildContext) {

    @Composable
    override fun View(modifier: Modifier) {
        AddServerScreen(
            onComplete = { finish() }
        )
    }
}
```

However builds fail with AGP 8.1.0-alpha04 with this error: `Class 'AddServerNode' is not abstract and does not implement abstract base class member public abstract val lifecycle: Lifecycle defined in com.bumble.appyx.core.node.Node`.

Appyx 1.0.3

Seems to have started happening after the latest canary/AGP update, any ideas?

**Comment by charlie-niekirk** [comment]
Seems the issue is actually directly as a result of updating Compose version from 1.4.0-alpha04 to 1.4.0-beta01, will do some investigation to see which compose dependency actually triggers this issue

**Comment by logickoder** [comment]
My fix for this was reverting my lifecycle dependencies from 2.6.0-beta01 back to 2.5.1 stable

**Comment by logickoder** [comment]
For now my only temporary hack is to annotate the overriden lifecycle fied with @get:JvmName("getNodeLifecycle")

**Comment by logickoder** [comment]
No, doesn't work, I get a null pointer exception

**Comment by KovalevAndrey** [comment]
Please make sure that you're using latest stable versions for [compose](https://developer.android.com/jetpack/androidx/releases/compose#2023.01.00) and [lifecycle](https://developer.android.com/jetpack/androidx/releases/lifecycle#lifecycle-*-2.5.1)

**Comment by charlie-niekirk** [comment]
Yep reverting compose material 3 to latest stable from latest alpha fixed my issue on another project. I'll close but is there a reason we can't use alpha versions of compose/lifecycle with Appyx? Also I may have missed something, but is this documented anywhere?

**Comment by KovalevAndrey** [comment]
@charlie-niekirk you're using lifecycle 2.6.0-beta01 where they introduces source incompatible [change](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.6.0-beta01)

<img width="917" alt="Screenshot 2023-02-13 at 11 34 33" src="https://user-images.githubusercontent.com/5773436/218447656-4007108f-9438-4f92-9565-19ed2acd3a74.png">


I will open an issue to mention all external dependencies for appyx
