### ISSUE TITLE
Shared element transition animation

### ISSUE THREAD

**Issue by brucemax** [bumble-tech/appyx#360]
Excuse me, but I did't find any info about shared element transition animation 
Is it possible to implement it with this lib. Could you provide an example?

**Comment by KovalevAndrey** [comment]
Hi @brucemax, shared element transition API is being implemented atm https://android-review.googlesource.com/c/platform/frameworks/support/+/2490596/10

We'll have to wait until the API is ready to experiment how we can integrate it into the library.

If you have any more questions please ask them in Discussion section
