### ISSUE TITLE
Bottom navigation like NowInAndroid(Google example app)

### ISSUE THREAD

**Issue by jeddchoi** [bumble-tech/appyx#366]
Hi, i'm investigating this library for bottom navigation use and looked into #307 .
I want to make bottom navigation like [Google's example app_Now in Android](https://github.com/android/nowinandroid/tree/main).

1. I'm not sure Spotlight is similar to above example app.
For NowInAndroid, there are 3 tabs-bottom navigation and when bottom navigation item is selected, code below is executed.

```kotlin
navController.navigate("some-route") {
    // Pop up to the start destination of the graph to
    // avoid building up a large stack of destinations
    // on the back stack as users select items
    popUpTo(
        navController.graph.findStartDestination().id
    ) {
        saveState = true
    }
    // Avoid multiple copies of the same destination when
    // reselecting the same item
    launchSingleTop = true
    // Restore state when reselecting a previously selected item
    restoreState = true
}
```

2. I know that document said 
> "Implements a mechanism analogous to a view pager; has a single active element ("it's in the spotlight", hence the name), but unlike the back stack, it does not remove other elements.".  

I'm afraid that it would take up a lot of memory when each tab's screen has many contents with Spotlight.
Also, I wonder that Spotlight would consider all lifecycle-things properly such as kotlin flow, coroutines in each screen's ViewModel(per tab). Would it pause and collect the flow properly?

3. Plus, `Spotlight.previous()` or `next()` is not desired usually for bottom navigation, I think.

Am I right in thinking? Should I make my own navModel class with BackStack? 
I saw [this project(which you mentioned in doc)](https://github.com/jbreitfeller-sfix/appyx-playground) also made bottom navigation with BackStack.(This project was different in back button handling with Now In Android)

Because I don't have much experience in Android dev, I apologize in advance.

**Comment by zsoltk** [comment]
Hey @jeddchoi, thanks for the issue!

1. A `Spotlight` instance can be used for displaying different tabs, yes.
2. As for memory, the related views are removed from the composition when off-screen. If you have additional objects living in the associated `Node` instance, they are kept alive for your convenience. This should be alright for most cases, however if you have heavy objects and wish, then yes, you could go for a `BackStack`. In this case you could use the `replace` operation to kill all nodes but the currently active one.
3. You could use the `activate` operation instead: https://bumble-tech.github.io/appyx/navmodel/spotlight/#activate

**Comment by zsoltk** [comment]
Also, I'd advise please use our https://github.com/bumble-tech/appyx/discussions page for questions in general.

**Comment by jeddchoi** [comment]
Thank you for kind explanation! I will check it out.
