### ISSUE TITLE
Accidental override conflict with androidx.lifecycle:lifecycle-runtime-ktx:2.6.0

### ISSUE THREAD

**Issue by Wysel** [bumble-tech/appyx#373]
I upgraded my project to androidx.lifecycle:lifecycle-runtime-ktx:2.6.0 and com.bumble.appyx:core:1.0.5.  After that I got following error:

Class SampleNode is not abstract and does not implement abstract base class member public abstract val lifecycle: Lifecycle defined in com.bumble.appyx.core.node.Node

Once I tried to override abstract property I got following:

Accidental override: The following declarations have the same JVM signature (getLifecycle()Landroidx/lifecycle/Lifecycle;):
    fun `<get-lifecycle>`(): Lifecycle defined in SampleNode fun getLifecycle(): Lifecycle defined in SampleNode

Any suggestion how to handle that?  Thanks.

**Comment by Wysel** [comment]
Here's LifecycleOwner prior to 2.6.0:

package androidx.lifecycle;
import androidx.annotation.NonNull;

public interface LifecycleOwner {
    @NonNull
    Lifecycle getLifecycle();
}

Here's LifecycleOwner 2.6.0+:

package androidx.lifecycle
import kotlinx.coroutines.CoroutineScope

public interface LifecycleOwner {
    public val lifecycle: Lifecycle
}

public val LifecycleOwner.lifecycleScope: LifecycleCoroutineScope
    get() = lifecycle.coroutineScope

**Comment by KovalevAndrey** [comment]
@Wysel please refer to this message https://github.com/bumble-tech/appyx/issues/350#issuecomment-1427795534

In order for you to use 2.6.0 we need to update it in the library

**Comment by Wysel** [comment]
Thanks Andrey.  Good to know you have it on your radar.  Do you have ETC available?

**Comment by KovalevAndrey** [comment]
@Wysel I've submitted the issue PRs are welcome :) Otherwise somebody from our team will pick it up

**Comment by KovalevAndrey** [comment]
Closing as the lifecycle has been updated
