### ISSUE TITLE
Update Lifefycle to 2.6.0

### ISSUE THREAD

**Issue by KovalevAndrey** [bumble-tech/appyx#376]
Update androix lifecycle to the[ latest stable release ](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.6.0)

https://github.com/bumble-tech/appyx/issues/373

**Comment by bmarty** [comment]
@KovalevAndrey maybe consider setting up [Renovate](https://github.com/apps/renovate) or Dependabot to maintain the dependencies up to date?

**Comment by KovalevAndrey** [comment]
> @KovalevAndrey maybe consider setting up [Renovate](https://github.com/apps/renovate) or Dependabot to maintain the dependencies up to date?

Hi @bmarty thanks for suggesting this. We'll consider this but the main problem here is that we have to align versions between Appyx and our main project and we can't always do it in the automated fashion. We strive to bring the dependencies up to date as soon as possible but sometimes we have to wait for some time
