### ISSUE TITLE
Interop Integrationpoint shouldn't force to expose appyx interface

### ISSUE THREAD

**Issue by SamuPS** [bumble-tech/appyx#53]
Current interop integration point required activities to implement `IntegrationPointAppyxProvider`.

This expose the interface in module edges, forcing parent modules to implement appyx event if they are not using it.

Example.

`Module A` -> `Module B`

`Module B` implements `SomeActiviy: RibAcitivty(), IntegrationPointAppyxProvider{...}`
`Module A` has no appyx dependencies.

Compilation failed as Module A will try to resolve  `IntegrationPointAppyxProvider`

**Comment by LachlanMcKee** [comment]
@SamuPS this should not be a problem in the next release of Appyx. Please let me know whether you still face a problem, and we can reopen this issue.
