### ISSUE TITLE
Upgrade Compose Multiplatform / Kotlin

### ISSUE THREAD

**Issue by manuel-martos** [bumble-tech/appyx#547]
Upgrade the following dependencies:
- Compose Multiplatform to `1.4.3`
- Kotlin to `1.9.0`
- KSP to `1.9.0-1.0.12`

These upgrades will bring the latest features and improvements to our project while ensuring compatibility with Kotlin 1.9.0 and the latest KSP version.

**Comment by ainoapp** [comment]
jb-compose 1.5.0-Beta01 was released and 1.5.0 will be release soon.

**Comment by ainoapp** [comment]
Please make appyx navigation for compose multiplatform
thank you

**Comment by zsoltk** [comment]
@ainoapp we're almost there: #551

**Comment by zsoltk** [comment]
Closing as done with even later versions in #662
