### ISSUE TITLE
Is this library applicable with dynamic feature modules 

### ISSUE THREAD

**Issue by chetanurmaliya** [bumble-tech/appyx#55]
Working on Jetpack Compose Navigation with multi module application using Kotlin DSL.
We have dynamic feature modules DFM1, DFM2, DFM3.

How to setup navigation graph and navigate between dynamic feature modules.

**Comment by zsoltk** [comment]
Hey @chetanurmaliya thanks for the question. Would you mind opening this discussion in https://github.com/bumble-tech/appyx/discussions? We've had dynamic feature modules support for [badoo/RIBs](https://github.com/badoo/RIBs), I assume the same can be done with Appyx too.

**Comment by chetanurmaliya** [comment]
Thanks @zsoltk 
Created a discussion: https://github.com/bumble-tech/appyx/discussions/58
