### ISSUE TITLE
Nested `BackPressHandler`s are ignored after app goes to background

### ISSUE THREAD

**Issue by steelahhh** [bumble-tech/appyx#60]
Haven't investigated the specifics, but here's the gist:
* Have a `ParentNode` with `BackStack` or `Modals` that has a leaf `ParentNode` that also has `BackStack`
* Push node to a nested `BackStack`
* Put the app in background 
* Open the app 
* Only the root `BackPressHandler` is called

Can be reproduced in sandbox app in "Combined routing source" or "Modal example" or "Spotlight example"

Edit: Looks like this would be fixed by #32 🤔

**Comment by CherryPerry** [comment]
Thanks for your report.
I checked the cases you provided in sandbox app and looks like my PR actually fixes it.
