### ISSUE TITLE
AppyxComponent copies elementUiModel on every frame when dragging

### ISSUE THREAD

**Issue by KovalevAndrey** [bumble-tech/appyx#619]
In AppyxComponent when we're dragging we're changing `transformedBoundingBox` that is backed by compose state. It invalidates the scope and makes `Child` composable recompose. When `Child` is recomposed it copies `elementUiModel`:

```
Child(
    elementUiModel = elementUiModel.copy(
        modifier = Modifier
            .offset { elementOffset }
            .pointerInput(appyxComponent) {
...
```

**Comment by zsoltk** [comment]
Done in #644
