### ISSUE TITLE
Reset node state when navigating to different element in spotlight

### ISSUE THREAD

**Issue by LukasAnda** [bumble-tech/appyx#633]
Hey there, I have a question.

I have a spotlight which presents a bunch of parent nodes. How can I force them to recreate when they are navigated to (e.g. ditch the backstack on them ? For now, when I navigate to the element, it keeps the backstack, which can be nice in certain situations, but I would prefer in this case to not to do it.

**Comment by LukasAnda** [comment]
Managed to solve it by doing `buildContext.copy(savedStateMap = null)` when resolving each child of the spotlight. But I am not sure if that is the correct way

**Comment by KovalevAndrey** [comment]
Hi @LukasAnda, Spotlight's purpose is to keep the same instance of Node per Navigation Target. If you need to create a new instance every time you navigate, perhaps you could use a BackStack + [replace](https://bumble-tech.github.io/appyx/components/backstack/#replace)?

On additional note, for questions please use Discussions tab

**Comment by zsoltk** [comment]
Or even better, come to **#appyx** on Slack.
