### ISSUE TITLE
Documentation error or maven error

### ISSUE THREAD

**Issue by brh** [bumble-tech/appyx#634]
The github pages list the below as the way to use material3:
 api("com.bumble.appyx:utils-material3:$version")

But it is listed as in maven repos
 api("com.bumble.appyx:material3:$version")

**Comment by AleksejB** [comment]
+1

docs listed:
```
implementation("com.bumble.appyx:utils-material3-android:$version")
```
as the dependency, but in reality it is:
```
implementation("com.bumble.appyx:material3-android:$version")
```

**Comment by zsoltk** [comment]
Hey @brh @AleksejB thanks for flagging! I believe it was an error that we released the new artifact id to the documentation earlier than we released the latest version to Maven. In the latest 2.0.0-alpha10 it should be under the documented id now.
