### ISSUE TITLE
Material 3 multiplatform tutorial error

### ISSUE THREAD

**Issue by eamedina87** [bumble-tech/appyx#659]
In the [Downloads](https://bumble-tech.github.io/appyx/releases/downloads/#material-3-support) tutorial  for multiplatform Material3 support there is an error regarding how to add the library to gradle.
This line:  
` api("com.bumble.appyx:utils-material3:$version")`
should be changed to: 
` api("com.bumble.appyx:material3:$version")`
Had to figure it out after exploring maven.

**Comment by zsoltk** [comment]
Hey @eamedina87 thanks for flagging! I believe it was an error that we released the new artifact id to the documentation earlier than we released the latest version to Maven. In the latest 2.0.0-alpha10 it should be under the documented id now.
