### ISSUE TITLE
SAMY im trying to contact you i want to purchaxe NEXTV 70 licences lifetime, however there is an issue with nextv entitlement please reach out to me desingtheweb@gmail.com

### ISSUE THREAD

**Issue by javielpro** [bumble-tech/appyx#709]
SAMY im trying to contact you i want to purchaxe NEXTV 70 licences lifetime, however there is an issue with nextv entitlement please reach out to me desingtheweb@gmail.com

**Comment by KovalevAndrey** [comment]
Irrelevant to Appyx
