### ISSUE TITLE
Consider introducing a Github merge queue 

### ISSUE THREAD

**Issue by LachlanMcKee** [bumble-tech/appyx#71]
Currently all branches are merged into main without requiring being up to date with main.

This could mean we merge an old branch that has a breaking change, and the main branch needs to be fixed.

Also, potentially if we introduce stricter static code analysis, potentially this older branch will increase our tech debt

We should consider using a merge queue to avoid this problem: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

Otherwise we could also enforce that all PRs need to be up to date with main, but I believe that will be far more annoying.

**Comment by LachlanMcKee** [comment]
Thoughts @CherryPerry / @zsoltk / @KovalevAndrey ?

**Comment by CherryPerry** [comment]
We do not need a merge queue but this option instead, it will be enough.

![option](https://docs.github.com/assets/cb-16239/images/help/repository/protecting-branch-loose-status.png)

**Comment by LachlanMcKee** [comment]
That's probably sufficient, however at least with the merge queue you don't need to keep updating, you just press merge and GitHub will manage multiple merges as long as there are no problems

**Comment by LachlanMcKee** [comment]
@KovalevAndrey / @zsoltk thoughts about requiring branches to be up to date? Will avoid master being broken accidentally

**Comment by zsoltk** [comment]
@LachlanMcKee it's enabled now.

**Comment by LachlanMcKee** [comment]
Thanks!
