### ISSUE TITLE
Gesture navigation

### ISSUE THREAD

**Issue by KovalevAndrey** [bumble-tech/appyx#97]
Explore and create an API for navigating with gestures

**Comment by amal** [comment]
Also please note Android 13 predictive back gesture. Support for it would be awesome!
https://developer.android.com/guide/navigation/predictive-back-gesture

**Comment by KovalevAndrey** [comment]
@amal I think it's already in place https://github.com/bumble-tech/appyx/pull/32

**Comment by amal** [comment]
@KovalevAndrey it's awesome, thank you!

**Comment by saket** [comment]
I'm curious, what's the reason for promoting this instead of encouraging people to use, say, horizontal pager from [Accompanist](https://google.github.io/accompanist/pager/)?

**Comment by LachlanMcKee** [comment]
@saket having a consistent API is one of the reasons. You could easy change from a full screen implementation to horizontal pager without a potentially substantial refactor.

**Comment by KovalevAndrey** [comment]
@saket `NavModel` at any given level of the tree coordinates [navigation of the subtree](https://bumble-tech.github.io/appyx/apps/structure/#composable-navigation). It allows us to keep our codebase organised in a tree structure, and use to use parent-child api, etc. Implementing it with, say, horizontal pager breaks this tree structure.

**Comment by zsoltk** [comment]
Closing as done in the scope of `2.x`
