### ISSUE TITLE
Drop com.bumble.appyx.core.minimal.reactive

### ISSUE THREAD

**Issue by CherryPerry** [bumble-tech/appyx#98]
We already have `attachWorkflow` and `waitForChildAttached` coroutine powered public API, so I think we can migrate copy-pasted from RIBs `PermissionRequestBoundary` to Flows.

Or we should commit to `minimal.reactive` and change `attachWorkflow`, `waitForChildAttached` implementations.

@zsoltk @KovalevAndrey @LachlanMcKee

**Comment by LachlanMcKee** [comment]
I agree that it would make sense to remove this, otherwise we should be adding reactive support for everything to be consistent. I don't think that is a good use of our time at the moment.
